# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# This fixes slowness when pasting commands
DISABLE_MAGIC_FUNCTIONS=true

# Load oh my zsh
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# I like menus
zstyle ':completion:*' menu select

[[ ! -f ~/.config/shells/common/common.sh ]] || source ~/.config/shells/common/common.sh
[[ ! -f ~/.config/shells/zsh/config/zplug.zsh ]] || source ~/.config/shells/zsh/config/zplug.zsh
[[ ! -f ~/.config/shells/zsh/config/p10k.zsh ]] || source ~/.config/shells/zsh/config/p10k.zsh
[[ ! -f ~/.config/shells/zsh/config/fzf.zsh ]] || source ~/.config/shells/zsh/config/fzf.zsh