# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# This fixes slowness when pasting commands
DISABLE_MAGIC_FUNCTIONS=true

# TMUX config
export DISABLE_AUTO_TITLE='true'

# Load oh my zsh
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Load completions added by homebrew
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
autoload -Uz compinit && compinit

# Style completions
#disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'

[[ ! -f ~/.config/shells/common/common.sh ]] || source ~/.config/shells/common/common.sh
[[ ! -f ~/.config/shells/zsh/config/zplug.zsh ]] || source ~/.config/shells/zsh/config/zplug.zsh
[[ ! -f ~/.config/shells/zsh/config/p10k.zsh ]] || source ~/.config/shells/zsh/config/p10k.zsh
[[ ! -f ~/.config/shells/zsh/config/fzf.zsh ]] || source ~/.config/shells/zsh/config/fzf.zsh
